// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUOTvE9v9LOSvd3BREWetlLSjeOuC9blo',
    appId: '1:947083927026:web:a804ae45bdf052841e9f6b',
    messagingSenderId: '947083927026',
    projectId: 'dermaphy-004',
    authDomain: 'dermaphy-004.firebaseapp.com',
    storageBucket: 'dermaphy-004.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBXDLNcHGUqsdXYZkRHSLXn7qRo4XaN1U',
    appId: '1:947083927026:android:bdf4c2330af303711e9f6b',
    messagingSenderId: '947083927026',
    projectId: 'dermaphy-004',
    storageBucket: 'dermaphy-004.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeHTxO5pxR75U9XbVuGwcnr509pRfBPwU',
    appId: '1:947083927026:ios:08ed5829a6f55dd11e9f6b',
    messagingSenderId: '947083927026',
    projectId: 'dermaphy-004',
    storageBucket: 'dermaphy-004.firebasestorage.app',
    iosBundleId: 'com.example.dermaphy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeHTxO5pxR75U9XbVuGwcnr509pRfBPwU',
    appId: '1:947083927026:ios:08ed5829a6f55dd11e9f6b',
    messagingSenderId: '947083927026',
    projectId: 'dermaphy-004',
    storageBucket: 'dermaphy-004.firebasestorage.app',
    iosBundleId: 'com.example.dermaphy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUOTvE9v9LOSvd3BREWetlLSjeOuC9blo',
    appId: '1:947083927026:web:1be0096a78f7fe9c1e9f6b',
    messagingSenderId: '947083927026',
    projectId: 'dermaphy-004',
    authDomain: 'dermaphy-004.firebaseapp.com',
    storageBucket: 'dermaphy-004.firebasestorage.app',
  );
}
